# ~/.config/cdactl/config.yaml

dotfile:
  repo_path: "/home/cdaprod/.cfg"
  remote_url: "git@github.com:Cdaprod/cda.cfg.git"
  branch_template: "{hostname}/{arch}"
  excludes:
    - ".git"

backup:
  backup_dir: "/home/cdaprod/backups"

ssh:
  default_user: "cdaprod"
  hosts:
    - name: "Work Server"
      host: "work.example.com"
      user: "workuser"
      port: 22
      key_path: "/home/user/.ssh/work_id_rsa"
    - name: "Home Server"
      host: "home.example.com"
      user: "homeuser"
      port: 2222
      key_path: "/home/user/.ssh/home_id_rsa"

network:
  default_interface: "eth0"

# Add more configurations as needed for other packages