name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # Ensure you're using a compatible Go version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies and tidy up Go modules
        run: |
          go mod tidy
          go mod download

      - name: Build binary
        run: go build -o ./cdactl ./cmd/cdactl/main.go

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check if Docker credentials exist
        run: echo "DOCKER_LOGIN=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV

      - name: Log in to DockerHub (if credentials exist)
        if: env.DOCKER_LOGIN != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (if logged in)
        if: env.DOCKER_LOGIN != ''
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cdactl:latest
            ${{ secrets.DOCKER_USERNAME }}/cdactl:${{ github.sha }}

      - name: Verify Docker Image
        run: docker run --rm ./cdactl help