name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Test
        run: go test ./...

      - name: Build
        run: go build -o cdactl

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cdactl
            man/cdactl.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}